import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import {
  exportPlan,
  generatePlan,
  generateTechnicalReport,
  getDut,
  getPlan,
  getResult,
  updatePlanItemStatus,
} from '../api'
import Spinner from '../components/Spinner'
import TestCard from '../components/TestCard'
import { downloadFromResponse } from '../utils/download'

export default function TestPlan() {
  const { dutId } = useParams()
  const [dut, setDut] = useState(null)
  const [tests, setTests] = useState([])
  const [resultsByTest, setResultsByTest] = useState({})
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [technicalReportCategory, setTechnicalReportCategory] = useState('all')
  const [generatingTechnicalReport, setGeneratingTechnicalReport] = useState(false)
  const [generatingAiTechnicalReport, setGeneratingAiTechnicalReport] = useState(false)

  useEffect(() => {
    loadData()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dutId])

  const loadResults = async (testList) => {
    const entries = await Promise.all(
      testList.map(async (test) => {
        try {
          const result = await getResult(test.id)
          return [test.id, result]
        } catch {
          return [test.id, null]
        }
      }),
    )
    setResultsByTest(Object.fromEntries(entries))
  }

  const loadData = async () => {
    setLoading(true)
    try {
      const dutData = await getDut(dutId)
      setDut(dutData)

      const planData = await getPlan(dutId)
      if (planData.tests && planData.tests.length > 0) {
        setTests(planData.tests)
        await loadResults(planData.tests)
      } else {
        await handleGenerate()
      }
    } catch (err) {
      toast.error(err.message || 'Data could not be loaded.')
    } finally {
      setLoading(false)
    }
  }

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const data = await generatePlan(dutId)
      setTests(data.tests)
      await loadResults(data.tests)
      if (data.source === 'fallback') {
        toast('AI service is unavailable. A fallback test plan is shown.', { icon: '!' })
      } else {
        toast.success('Test plan generated by the AI service.')
      }
    } catch (err) {
      toast.error(err.message || 'Test plan could not be generated.')
    } finally {
      setGenerating(false)
    }
  }

  const handleExport = async () => {
    setExporting(true)
    const toastId = toast.loading('Downloading test plan...')
    try {
      const response = await exportPlan(dutId)
      downloadFromResponse(response, `TestPlan_${dut?.name || dutId}.docx`)
      toast.success('Test plan downloaded.', { id: toastId })
    } catch (err) {
      toast.error(err.message || 'Test plan could not be downloaded.', { id: toastId })
    } finally {
      setExporting(false)
    }
  }

  const handleGenerateTechnicalReport = async () => {
    setGeneratingTechnicalReport(true)
    const toastId = toast.loading('Generating technical report...')
    try {
      const response = await generateTechnicalReport(dutId, technicalReportCategory)
      downloadFromResponse(response, `TechnicalReport_${dut?.name || dutId}.docx`)
      toast.success('Technical report downloaded.', { id: toastId })
    } catch (err) {
      toast.error(err.message || 'Technical report could not be generated.', { id: toastId })
    } finally {
      setGeneratingTechnicalReport(false)
    }
  }

  const handleGenerateAiTechnicalReport = async () => {
    setGeneratingAiTechnicalReport(true)
    const toastId = toast.loading('Generating AI-assisted technical report...')
    try {
      const response = await generateTechnicalReport(dutId, technicalReportCategory, true)
      downloadFromResponse(response, `AI_TechnicalReport_${dut?.name || dutId}.docx`)
      toast.success('AI-assisted technical report downloaded.', { id: toastId })
    } catch (err) {
      toast.error(err.message || 'AI-assisted technical report could not be generated.', { id: toastId })
    } finally {
      setGeneratingAiTechnicalReport(false)
    }
  }

  const handlePlanItemStatusChange = async (test, status) => {
    if (!test.test_plan_item_id) return
    try {
      const updated = await updatePlanItemStatus(test.test_plan_item_id, status)
      setTests((prev) =>
        prev.map((item) =>
          item.id === test.id
            ? { ...item, plan_item_status: updated.status, plan_item_updated_at: updated.updated_at }
            : item,
        ),
      )
      toast.success('Plan item status updated.')
    } catch (err) {
      toast.error(err.message || 'Plan item status could not be updated.')
    }
  }

  if (loading) {
    return <Spinner size="lg" label="Loading DUT and test plan..." />
  }

  if (!dut) {
    return (
      <div className="card text-center text-slate-300">
        <p>DUT was not found.</p>
        <Link to="/dut" className="btn-primary mt-4 inline-flex">
          Back to DUT Registration
        </Link>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="card flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-100">{dut.name}</h1>
          <p className="mt-1 text-sm text-slate-400">
            {dut.manufacturer} - {dut.part_number} - {dut.customer} / {dut.project}
          </p>
          <p className="mt-2 text-sm text-slate-400">
            Review AI-selected ISO 16750 tests and manage execution status.
          </p>
          <p className="mt-1 text-xs text-slate-500">
            {dut.mounting_location} - {dut.nominal_voltage} - {dut.power_class} -{' '}
            {dut.temp_min} C / {dut.temp_max} C - IP: {dut.ip_class || '-'}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            className="btn-secondary"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? 'Generating...' : 'Regenerate Test Plan'}
          </button>
          <button
            type="button"
            className="btn-primary"
            onClick={handleExport}
            disabled={exporting || tests.length === 0}
          >
            {exporting && (
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-navy border-t-transparent" />
            )}
            {exporting ? 'Downloading...' : 'Download Test Plan (.docx)'}
          </button>
        </div>
      </div>

      <div className="card flex flex-col gap-3 border-amber/30 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h2 className="text-lg font-semibold text-amber">Technical Report</h2>
          <p className="mt-1 text-sm text-slate-400">
            Generate a final ISO 16750 technical report for the selected category.
          </p>
          {tests.length === 0 && (
            <p className="mt-2 text-xs text-slate-500">
              Generate a test plan before creating the technical report.
            </p>
          )}
        </div>
        <div className="flex flex-col gap-2 sm:flex-row sm:items-end">
          <div>
            <label className="label-field" htmlFor="technical_report_category">
              Category
            </label>
            <select
              id="technical_report_category"
              className="input-field min-w-48"
              value={technicalReportCategory}
              onChange={(event) => setTechnicalReportCategory(event.target.value)}
            >
              <option value="electrical">Electrical</option>
              <option value="environmental">Environmental</option>
              <option value="chemical">Chemical</option>
              <option value="all">All</option>
            </select>
          </div>
          <button
            type="button"
            className="btn-primary"
            onClick={handleGenerateTechnicalReport}
            disabled={generatingTechnicalReport || generatingAiTechnicalReport || tests.length === 0}
          >
            {generatingTechnicalReport ? 'Generating...' : 'Generate Technical Report'}
          </button>
          <button
            type="button"
            className="btn-secondary"
            onClick={handleGenerateAiTechnicalReport}
            disabled={generatingTechnicalReport || generatingAiTechnicalReport || tests.length === 0}
          >
            {generatingAiTechnicalReport ? 'Generating with AI...' : 'Generate with AI'}
          </button>
        </div>
      </div>

      {generating ? (
        <Spinner
          size="lg"
          label="Generating ISO 16750 test plan with the AI service. This may take a few minutes..."
        />
      ) : tests.length === 0 ? (
        <div className="card text-center text-slate-400">
          No test plan exists for this DUT yet. Use Regenerate Test Plan to create AI-assisted ISO 16750 test selections.
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
          {tests.map((test) => (
            <TestCard
              key={test.id}
              dutId={dutId}
              test={test}
              result={resultsByTest[test.id]}
              onPlanItemStatusChange={handlePlanItemStatusChange}
            />
          ))}
        </div>
      )}
    </div>
  )
}
